${TEMPLATE_BUILDER}

FROM ${DEBIAN_IMAGE}
RUN set -ex; \
	apt-get update; \
	DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
		iputils-ping \
		dnsutils \
		openssh-client \
		rsync \
		curl \
		jq \
	; \
	apt-get clean; \
	rm -rf /var/lib/apt/lists/*
${TEMPLATE_FACADE}
