name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        file: ./scratch/Dockerfile
        tags:
        - sstc/kala:latest
        - sstc/kala:scratch
    - uses: docker/build-push-action@v2
      with:
        push: true
        file: ./debian/Dockerfile
        tags: sstc/kala:debian
    - uses: docker/build-push-action@v2
      with:
        push: true
        file: ./alpine/Dockerfile
        tags: sstc/kala:alpine
    - uses: docker/build-push-action@v2
      with:
        push: true
        file: ./all/Dockerfile
        tags: sstc/kala:all
    - uses: up9cloud/action-notify@master
      if: cancelled() == false
      env:
        GITHUB_JOB_STATUS: ${{ job.status }}
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
